# Generated by Django 4.1.3 on 2025-03-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='modile',
            new_name='mobile',
        ),
    ]
