# Generated by Django 5.1.7 on 2025-03-26 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_remove_user_name_user_is_admin_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='task_manager.user'),
        ),
    ]
